### ISSUE TITLE
add mainClassName to generated build.gradle 

### ISSUE THREAD

**Issue by joprice** [IntelliJ-Frege/intellij-frege#109]
I generated a project with intellij, then tried using the `fregeRun` and `run` tasks, but I get the following error:
 
```
./gradlew fregeRun

> Task :fregeRun FAILED
Error: Unable to access jarfile /Users/josephprice/dev/frege-scratch/build/classes/java/main:/Users/josephprice/dev/frege-scratch/build/resources/main:/Users/josephprice/dev/frege-scratch/lib/org/frege-lang/frege/3.25.84/frege-3.25.84.jar
```

Eventually I guessed that the `mainClassName` needed to be configured and that worked. Maybe the template could include a mostly empty module that prints hello world with the class name configured just so it's obvious what to configure (and avoid bug reports).

**Comment by 23jura23** [comment]
Yes, that sounds reasonable. I am not sure that the template should include an empty Hello world files as, for example, Java does not include them, but a hint or explanation about `mainClassName` is definitely needed, I will add it

The implied behavior is similar to IDEA for Java:
1. Create a Frege file
2. Write a `main` function with 0 or 1 argument
3. IDEA shows you a green triangle to the left of code (on gutter)
4. Click on it and then click Run

Then it will specify main class while running `./gradlew fregeRun` using `-Pclass_name=` option. The entire command will now look like `./gradlew fregeRun -Pclass_name=myPackageName.myClassName`

If no `-Pclass_name` specified, it will use `mainClassName` variable in `build.gradle` or in `gradle.properties`.

My bad, the build system needs a usage instruction to be written :(

**Comment by kkarnauk** [comment]
We decided that the provided functionality (with starting a program using the green triangle) is enough for now to use our plugin. So, I'm closing this issue.
