### ISSUE TITLE
"package"-visible members are not exported by default but treated as such by the plugin

### ISSUE THREAD

**Issue by Dierk** [IntelliJ-Frege/intellij-frege#70]
e.g. `PreludeList` defines the `intersperse` function as package-visible.
In order to access this function, Frege code needs to explicitly import `Data.List`.
But the plugin shows usages of `intersperse` as correct without the import - but then executing the code fails.

```
main  = do
    println $ intersperse 0 [1,2,3]
```

**Comment by kkarnauk** [comment]
Thanks! Fixed.
